name: meatlogger
description: Meatlogger
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_analytics: ^10.0.3
  provider: ^6.0.3
  flutterfire_ui: ^0.4.3+20
  rxdart: ^0.27.7
  jiffy: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  syncfusion_flutter_charts: ^20.4.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"  
flutter:
  uses-material-design: true
